GET  http://localhost:4000/employees 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5MjI3NTQ3LCJleHAiOjE3MDkyMjg0NDd9.A9qBK9Rgd3jXtoODwFdVqU2uqlEFXPM8nqRFvYxsA6o

###

POST http://localhost:3000/login 
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "adminexample@"
}