GET  http://localhost:4000/employees 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5MjkxOTEzLCJleHAiOjE3MDkyOTE5NDh9.NQdO2fQZhVcoGVCLcYxfVCPlNtgmV1O2GB6qq70QlfM



###

POST http://localhost:3000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5MjkxNzg4fQ.RUuC2RO4i59Uz4fayIUC1pFJgFcJE7r92_llGgHXydM"
}


###

POST http://localhost:3000/login 
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "adminexample@"
}