GET  http://localhost:4000/employees 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJpYXQiOjE3MDkyODE1MTEsImV4cCI6MTcwOTI4MTU0Nn0.QU7-8WC1EtV2vUCexzW4GewcezpCrDtLtWl6lH2Z9Ss



###

POST http://localhost:3000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJpYXQiOjE3MDkyODE0NzR9.jcycwAENEvVMOHTUrPH-7WzUWktHr-AFxUH6HWiXQfg"
}


###

POST http://localhost:3000/login 
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "adminexample@"
}