GET  http://localhost:4000/employees 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5MzA3MzA1LCJleHAiOjE3MDkzMDczNDB9.i-AqMreKhwMNyDK9E-5hrQlfeQfXNR-AfElS-2FQSbE


###

POST http://localhost:3000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5MzA3MjY1fQ._IoXmrp8ZDBCpLk2Jrms5-_ZgA5TZqKcQcem5Rho0Dk"
}


###

POST http://localhost:3000/login 
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "adminexample@"
}