GET http://localhost:4000/employees 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5Mzc3OTUyLCJleHAiOjE3MDkzNzc5ODd9.PPVTl7YKSXkC0tqPfK9HRoIrT04XuNqS8BDi5Jk4n2U

###

POST http://localhost:3000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5NDc2MjcyLCJleHAiOjE3MDk0NzY1NzJ9.lTPnBAT-noSII2TNzQ0t36Ci5UWDH0yXJ0I1_JGFWmc"
}

### removes the associated refresh token to the user who will logouut 
DELETE http://localhost:3000/logout 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5Mzc3OTUyLCJleHAiOjE3MDkzNzgyNTJ9.1xubR-Xo94o1uDZ_OIj2hzO5dIV77YnDJtxZCHPuhgo"
}


### 
POST http://localhost:3000/login 
Content-Type: application/json

{
    "email": "john.doe@example.com", 
    "password": "adminexample@"
}

### 
GET http://localhost:4000/emp/employees 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRlZWFkZGY0YzI3NDQyM2I2NmQ1MWEiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5MzgzNjkxLCJleHAiOjE3MDkzODM3MjZ9.WZXNK-V_jHM-MBpotroeKdPW-QiOhKa9NvJIvh1O_jw